In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

# Process Participation Data

### Load the Participation Data

In [2]:
participation = pd.read_pickle('../../data/raw/participation_data')

In [3]:
participation.head()

,authenticated,duration,extra,index_,magnitude,origin,profile,profile_origin,profile_referrer,profile_utm_campaign,profile_utm_content,profile_utm_medium,profile_utm_source,profile_utm_term,project,repetitions,type,when,where
0,True,0,,1,1,Unspecified,c3174748ab29f73d8c6226d0c2171aeb,,,,,,,,25.0,1,Participated,2016-07-22 14:07:43,NaN
1,True,0,,2,1,Unspecified,c3174748ab29f73d8c6226d0c2171aeb,,,,,,,,25.0,1,Participated,2016-08-26 17:43:54,NaN
2,True,0,,3,1,Unspecified,59d1c4ccba844b6f4722d2967c531441,,,,,,,,25.0,1,Participated,2016-08-26 17:46:32,NaN
3,True,0,,4,1,Unspecified,59d1c4ccba844b6f4722d2967c531441,,,,,,,,25.0,1,Participated,2016-08-26 17:48:18,NaN
4,True,0,,5,1,Unspecified,59d1c4ccba844b6f4722d2967c531441,,,,,,,,25.0,1,Participated,2016-08-28 23:57:25,NaN

In [4]:
participation.describe()

        duration        index_     magnitude       project  repetitions
count  1474748.0  1.474748e+06  1.474748e+06  1.261569e+06    1474748.0
mean         0.0  7.373751e+05  1.746123e+01  1.369494e+03          1.0
std          0.0  4.257236e+05  1.783508e+01  2.715116e+03          0.0
min          0.0  1.000000e+00  0.000000e+00  4.000000e+00          1.0
25%          0.0  3.686878e+05  1.000000e+00  1.014000e+03          1.0
50%          0.0  7.373755e+05  1.000000e+00  1.014000e+03          1.0
75%          0.0  1.106062e+06  3.900000e+01  1.014000e+03          1.0
max          0.0  1.474749e+06  4.000000e+01  2.065500e+04          1.0

### One-Hot Encoding the type field

#### Clean the values

In [5]:
def reformat_type(text):
    return text.replace(' ', '_').replace('/', 'or')

participation['type'] = participation['type'].apply(reformat_type)

#### Add new one-hot encoding for type column

In [6]:
type_dataframe = pd.get_dummies(participation['type'],prefix='type')

In [7]:
participation = participation.join(type_dataframe)

In [8]:
participation.head()

,authenticated,duration,extra,index_,magnitude,origin,profile,profile_origin,profile_referrer,profile_utm_campaign,...,type_Marked_themselves_a_participant,type_Negate_previous_event,type_OAuth_Login,type_Participated,type_Rated_the_project,type_Removed_a_bookmark,type_Removed_from_dashboard,type_Search_in_finder,type_Started_a_project,type_Viewed_a_profile
0,True,0,,1,1,Unspecified,c3174748ab29f73d8c6226d0c2171aeb,,,,...,0,0,0,1,0,0,0,0,0,0
0,True,0,,1,1,Unspecified,c3174748ab29f73d8c6226d0c2171aeb,,,,...,0,0,0,0,0,0,0,0,0,0
0,True,0,,1,1,Unspecified,c3174748ab29f73d8c6226d0c2171aeb,,,,...,0,0,0,1,0,0,0,0,0,0
0,True,0,,537250,39,Unspecified,5aab8db0481044218e02eb042e95dd8d,,https://blog.eyesonalz.com/top-10-citizenscien...,,...,0,0,0,1,0,0,0,0,0,0
0,True,0,,537250,39,Unspecified,5aab8db0481044218e02eb042e95dd8d,,https://blog.eyesonalz.com/top-10-citizenscien...,,...,0,0,0,0,0,0,0,0,0,0

### Explore the participation

In [9]:
participation.describe()

,duration,index_,magnitude,project,repetitions,type_Added_a_bookmark,type_Added_to_dashboard,type_Asked_a_question,type_Bookmarked_the_project,type_Classification_or_Transcription,...,type_Marked_themselves_a_participant,type_Negate_previous_event,type_OAuth_Login,type_Participated,type_Rated_the_project,type_Removed_a_bookmark,type_Removed_from_dashboard,type_Search_in_finder,type_Started_a_project,type_Viewed_a_profile
count,3045646.0,3.045646e+06,3.045646e+06,2.625379e+06,3045646.0,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,...,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06
mean,0.0,5.634865e+05,1.510397e+01,1.346708e+03,1.0,1.666083e-02,1.010295e-02,1.050680e-05,1.734312e-02,4.181290e-01,...,2.926801e-03,1.761531e-03,2.758036e-05,3.278503e-01,1.172165e-04,1.208611e-03,4.714927e-04,1.273139e-01,3.283376e-07,8.619518e-03
std,0.0,3.804162e+05,1.744207e+01,2.537021e+03,0.0,1.279971e-01,1.000044e-01,3.241403e-03,1.305463e-01,4.932517e-01,...,5.402070e-02,4.193362e-02,5.251629e-03,4.694300e-01,1.082602e-02,3.474407e-02,2.170877e-02,3.333243e-01,5.730075e-04,9.244038e-02
min,0.0,1.000000e+00,0.000000e+00,4.000000e+00,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.0,2.538042e+05,1.000000e+00,1.014000e+03,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,0.0,5.132110e+05,1.000000e+00,1.014000e+03,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,0.0,7.750280e+05,3.700000e+01,1.014000e+03,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,0.0,1.474749e+06,4.000000e+01,2.065500e+04,1.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

### Drop some columns

In [10]:
participation = participation.drop(columns=['duration', 'repetitions'])

In [11]:
participation.describe()

,index_,magnitude,project,type_Added_a_bookmark,type_Added_to_dashboard,type_Asked_a_question,type_Bookmarked_the_project,type_Classification_or_Transcription,type_Clicked_to_join_the_project,type_Data_collection,...,type_Marked_themselves_a_participant,type_Negate_previous_event,type_OAuth_Login,type_Participated,type_Rated_the_project,type_Removed_a_bookmark,type_Removed_from_dashboard,type_Search_in_finder,type_Started_a_project,type_Viewed_a_profile
count,3.045646e+06,3.045646e+06,2.625379e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,...,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06,3.045646e+06
mean,5.634865e+05,1.510397e+01,1.346708e+03,1.666083e-02,1.010295e-02,1.050680e-05,1.734312e-02,4.181290e-01,2.534766e-02,7.501528e-03,...,2.926801e-03,1.761531e-03,2.758036e-05,3.278503e-01,1.172165e-04,1.208611e-03,4.714927e-04,1.273139e-01,3.283376e-07,8.619518e-03
std,3.804162e+05,1.744207e+01,2.537021e+03,1.279971e-01,1.000044e-01,3.241403e-03,1.305463e-01,4.932517e-01,1.571788e-01,8.628591e-02,...,5.402070e-02,4.193362e-02,5.251629e-03,4.694300e-01,1.082602e-02,3.474407e-02,2.170877e-02,3.333243e-01,5.730075e-04,9.244038e-02
min,1.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.538042e+05,1.000000e+00,1.014000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,5.132110e+05,1.000000e+00,1.014000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,7.750280e+05,3.700000e+01,1.014000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.474749e+06,4.000000e+01,2.065500e+04,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

### Group by Project and Profile

In [12]:
profile_project_interactions = participation.groupby(['profile','project']).size().reset_index()

In [13]:
profile_project_interactions['num_interactions'] = profile_project_interactions[0]
profile_project_interactions = profile_project_interactions.drop(columns=0)

In [14]:
profile_project_interactions.head()

                            profile  project  num_interactions
0  000073c3675ea9a1d0fe0ee3ca57e2bf    413.0                 6
1  0002b85e757486c6d80ed6f73f465eaa  16864.0                 3
2  0003a41bbdb3371df4c1829913f17537  19794.0                 1
3  000436aaa487e461e6e16e02ab3e89eb    659.0                 3
4  000476d8680db78d75b3b9edefc4a6d2   1510.0                 1

In [15]:
profile_project_interactions.sort_values(by='num_interactions', ascending=False)

                                 profile  project  num_interactions
35719   5aab8db0481044218e02eb042e95dd8d   1014.0            455319
95477   f512f2afac71936a18d212929f30a9db   1014.0            253989
4465    0bb971b361b9fcc5c62f107149901df6   1014.0            202287
64357   a5015692c9fabeed95ff84469768ef20   1014.0            173026
65897   a900f4940eb7a493c3ed1239636e3438   1014.0            156110
15782   299a04f44bdef72485d628557c056d8a   1014.0            100175
20241   3492d8f7af1fd35a3fcd2e91e94ac301   1014.0             96965
8262    1546695d482d49e51146efaab7fae423   1014.0             85040
15630   291f5dc8c587ad44a093f001d71627a8   1014.0             72018
55972   8f52d4c68da61cc0dab830ed40fd970e   1014.0             46488
61333   9d3b3f3aea284ab9732ff55c85e0d2dd   1014.0             45147
93241   eedbed105b6a567853831c26cd7e124b   1014.0             42739
45373   74138d65e25623df7fd799eb4f0ec7be   1014.0             39831
10792   1c5e58e6fe8a1d216fe19f5aeb388793   1014.0             36788
28730   495528e3ddc772e8bfe09f0efc68a943   1014.0             33993
82114   d29feb1185913d0dc4ee3a7aeff97ded   1014.0             25389
8678    1678fa0c42aedef0594df35df13d161a   1014.0             22044
96500   f793bc3741c915b0139da9c6aeb679b9   1014.0             20502
17338   2dbee84fad9b8550901d44a594701f05   1014.0             19563
74074   be050399b090b99717beecacd5fc611b   1014.0             19202
84712   d94f55d63a581cd8041726e795f49400   1014.0             13517
94003   f0f780c8356cc00e1e3c7da87960462b   1014.0             12740
51090   836523ac27f403499f595a3a481b171e   1014.0             12679
80204   cdf3442c67095952427f82c2975fc88d   1380.0             11695
520     015483857befe09cad7de1594b80421d   1014.0             11223
38704   633c07830093bb7aae0f0b1760e6b24e   1014.0             10449
76046   c2f1764ad77564bae577a80baf59bcc6   1014.0             10246
74554   bf5ab832fdbdf56af31913a9b1e87388   1014.0              8391
23588   3c7304b9bef5ae7b0735c24a0b8aff6e   1014.0              8100
17838   2f24ed781c2c52aa3d8b1824d5ade45b   1014.0              7506
...                                  ...      ...               ...
50163   80ee718d2aaae6df22352c2b2f19e90e     25.0                 1
50165   80ef13f2a617971426b9f45a94e0e525  16830.0                 1
50166   80f0f13431b1049addd8d5cf1f7cac26     25.0                 1
50168   80f13d5f5befd822a86ec4b45ef428dd     25.0                 1
50169   80f14503c3ca3cd3b6c34117e79dd85b     25.0                 1
50114   80c5eb81c71df6d2e8c2169d8f10bfd2     25.0                 1
50113   80c4e2d65802cab682847c75c1d9e572  19794.0                 1
50112   80c4ac768b57c5501e7ad6663db423bb     25.0                 1
50067   80aa8c62df73e4b6d3567f2fbeee777c     25.0                 1
50037   809a1a0ec05ce73f056427611c9bda9e     25.0                 1
50038   809b1702cdf3db655e05b9e503b3f87c     25.0                 1
50039   809b4eb5c6ab6eaa2da8be27e14b2f6b     25.0                 1
50040   809d99be1d412704b396a1264ef1186a     25.0                 1
50057   80a1cbe85b23a7d6251d538f20a3c219     25.0                 1
50059   80a29bb08b12049e7ee26d38440b67c3    268.0                 1
50060   80a3cd553d9e2d63e4d2abc079da02e9     25.0                 1
50064   80a5ae7d2378ee4d3027486d9785b9f9     25.0                 1
50065   80a6d0757a75bfb29dbef314936ecacc     25.0                 1
50068   80abe46064e03753e1cdca4dca134288     25.0                 1
50111   80c3ed12cf18923fe7dd0ef42f2c344b     25.0                 1
50070   80ad75c8c26e1b7a2b81fcf98e9cb727     25.0                 1
50074   80b427eb48fd43a3823051317ec860fd     25.0                 1
50077   80b58f79eb75859dc1b83e1c929cefe8  19794.0                 1
50079   80b726f7fff35d58544277da70e2a312     25.0                 1
50080   80b79ea52dd3684950908141a25c10fc     25.0                 1
50086   80bd03bcf60dd88665edbeb884ff4d08     25.0                 1
50088   80be078b1553423e7cb65e05646a4838     25.0                 1
50093   80c12ae82fcb2e8ab1eb7f9afb6bb1a6     25.0                 1
50109   80c30037a435e04862e886d717bf6cd7     25.0                 1
100082  ffffef31f9eb8792a15ecd5d67cdfd79    636.0                 1

[100083 rows x 3 columns]