In [9]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import json
from pandas.io.json import json_normalize

## Restructure the Participation Data

In [10]:
participations = pd.read_pickle('../../data/raw/participation_data')

In [11]:
len(participations)

1474748

In [12]:
participations.describe()

        duration        index_     magnitude       project  repetitions
count  1474748.0  1.474748e+06  1.474748e+06  1.261569e+06    1474748.0
mean         0.0  7.373751e+05  1.746123e+01  1.369494e+03          1.0
std          0.0  4.257236e+05  1.783508e+01  2.715116e+03          0.0
min          0.0  1.000000e+00  0.000000e+00  4.000000e+00          1.0
25%          0.0  3.686878e+05  1.000000e+00  1.014000e+03          1.0
50%          0.0  7.373755e+05  1.000000e+00  1.014000e+03          1.0
75%          0.0  1.106062e+06  3.900000e+01  1.014000e+03          1.0
max          0.0  1.474749e+06  4.000000e+01  2.065500e+04          1.0

In [13]:
participations.tail()

,authenticated,duration,extra,index_,magnitude,origin,profile,profile_origin,profile_referrer,profile_utm_campaign,profile_utm_content,profile_utm_medium,profile_utm_source,profile_utm_term,project,repetitions,type,when,where
289042,True,0,,537244,40,Unspecified,299a04f44bdef72485d628557c056d8a,,https://stallcatchers.com/virtualMicroscope?au...,,,,,,1014.0,1,Classification / Transcription,2017-08-17 21:02:49,NaN
289043,True,0,,537245,40,Unspecified,299a04f44bdef72485d628557c056d8a,,https://stallcatchers.com/virtualMicroscope?au...,,,,,,1014.0,1,Classification / Transcription,2017-08-17 21:02:54,NaN
289044,True,0,,537246,40,Unspecified,299a04f44bdef72485d628557c056d8a,,https://stallcatchers.com/virtualMicroscope?au...,,,,,,1014.0,1,Classification / Transcription,2017-08-17 21:03:00,NaN
289045,True,0,,537247,40,Unspecified,299a04f44bdef72485d628557c056d8a,,https://stallcatchers.com/virtualMicroscope?au...,,,,,,1014.0,1,Classification / Transcription,2017-08-17 21:03:06,NaN
289046,True,0,,537248,40,Unspecified,299a04f44bdef72485d628557c056d8a,,https://stallcatchers.com/virtualMicroscope?au...,,,,,,1014.0,1,Classification / Transcription,2017-08-17 21:03:14,NaN

## Restructure the Project Data

In [14]:
projects = pd.read_pickle('../Data/project_data')

In [15]:
len(projects)

1781

In [16]:
projects.head()

,UN_regions,country,description,error,guid,origin,regions,tags,title,topics,url,project_id
0,[],,Foldit is a revolutionary new computer game en...,NaN,5f80760d-8398-5091-b3c6-f34c39216e88,scistarter,[],"[dna, protein]",Foldit,"[Computers & Technology, Biology, Chemistry]",https://scistarter.com/project/4-Foldit-Foldit,4
1,[],,Firefly Watch combines an annual summer evenin...,NaN,c9664e0c-819a-5a42-b4bb-5f25d83a486d,scistarter,"[{'geometry': {'type': 'MultiPolygon', 'coordi...","[boston, cambridge, fireflies, insects, lightn...",Firefly Watch,"[Nature & Outdoors, Animals, Ecology & Environ...",https://scistarter.com/project/5-Firefly-Watch...,5
2,[],,Galaxy Zoo needs your help to classify galaxie...,NaN,11f65e99-b463-5e01-ac11-ae59c021dfe7,scistarter,[],"[astronomy & space, space, space science, zoon...",Galaxy Zoo,"[Astronomy & Space, Computers & Technology]",https://scistarter.com/project/6-Galaxy-Zoo-Ga...,6
3,[],None,Pay attention to the plants and animals in you...,NaN,wilsoncenter:27-107,scistarter,"[{'geometry': {'type': 'MultiPolygon', 'coordi...","[android, animal, animals, app, biology, clima...",Nature's Notebook,"[Ocean, Water, Marine & Terrestrial, Education...",https://scistarter.com/project/7-Natures-Noteb...,7
4,[],,A recent issue of Make magazine (http://makezi...,NaN,ae91e967-6eec-5aef-ab3a-7d86ceff737a,scistarter,[],[],Laser Harp: Build It Yourself,"[Computers & Technology, Sound, Physics]",https://scistarter.com/project/8-Laser-Harp-Bu...,8