In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import json
from pandas.io.json import json_normalize
from scipy import sparse

### Load in our data from pickle files

In [2]:
# Check if there are any missing projects in 
projects = pd.read_pickle("../Data/project_data")

In [3]:
projects.shape

(1781, 12)

In [4]:
profilesProjects = pd.read_pickle('../Data/useful_profile_project_adj')

In [5]:
profilesProjects.shape

(4866, 1220)

### Add/Remove columns

In [6]:
project_ids = list(projects['project_id'])
count = 0
# Add any missing columns
for project_id in project_ids:
    if project_id not in profilesProjects.columns:
        profilesProjects[project_id] = 0

print(profilesProjects.shape)
        
# Remove any columns that aren't in project_data
cols = profilesProjects.columns.tolist()
for col in cols:
    if col not in list(projects['project_id']):
        profilesProjects = profilesProjects.drop(columns=[col])
    
print(profilesProjects.shape)

(4866, 1783)
(4866, 1781)

In [7]:
profilesProjects.head()

project,4.0,5.0,6.0,7.0,8.0,19.0,20.0,22.0,24.0,25.0,...,296.0,297.0,298.0,302.0,303.0,304.0,309.0,310.0,312.0,19847.0
profile,,,,,,,,,,,,,,,,,,,,,
001bedb58aa43c8d3596b5b522ba1040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0021e5df03d7feb6ba9558cc2828d616,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
00300cba5401183830a6a82b80c8ff7f,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0033882471572a66322d0747c6a4b12d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
00536e1575193e409e255cd02ed9d205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Rearrange Columns

In [8]:
cols = profilesProjects.columns.tolist()

In [9]:
for col in cols:
    if col == None:
        print('hello')

In [10]:
cols.sort()

In [11]:
profilesProjects = profilesProjects[cols]

In [12]:
profilesProjects.head()

project,4.0,5.0,6.0,7.0,8.0,19.0,20.0,22.0,23.0,24.0,...,20571.0,20572.0,20573.0,20577.0,20591.0,20603.0,20637.0,20645.0,20650.0,20655.0
profile,,,,,,,,,,,,,,,,,,,,,
001bedb58aa43c8d3596b5b522ba1040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0021e5df03d7feb6ba9558cc2828d616,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
00300cba5401183830a6a82b80c8ff7f,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0033882471572a66322d0747c6a4b12d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
00536e1575193e409e255cd02ed9d205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
profilesProjects = profilesProjects.reset_index(level='profile')

In [14]:
profilesProjects.head()

project,profile,4.0,5.0,6.0,7.0,8.0,19.0,20.0,22.0,23.0,...,20571.0,20572.0,20573.0,20577.0,20591.0,20603.0,20637.0,20645.0,20650.0,20655.0
0,001bedb58aa43c8d3596b5b522ba1040,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0021e5df03d7feb6ba9558cc2828d616,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,00300cba5401183830a6a82b80c8ff7f,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0033882471572a66322d0747c6a4b12d,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,00536e1575193e409e255cd02ed9d205,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
profilesProjects.to_pickle("./multiple_profile_all_projects")