In [1]:
import pandas as pd
import json
import numpy as np

In [23]:
# Read results
results = pd.read_json('../../data/experiment-results/cf-autoencoder/train_autoencoder_128_cdae_users_projects_5.json', lines=True)

results = results.T
results['json'] = results[0]

newDataframe = pd.DataFrame(columns=['user_index', 'precision', 'recall', 'y_pred', 'y_true', 'len_yPred', 'len_yTrue'])
newDataframe['y_pred'] = newDataframe['y_pred'].astype(object)
newDataframe['y_true'] = newDataframe['y_true'].astype(object)

for index, row in results.iterrows():
    newSeries = pd.Series(index=['user_index', 'precision', 'recall', 'y_pred', 'y_true', 'len_yPred', 'len_yTrue'])
    newSeries['y_pred'] = newSeries['y_pred'].astype(object)
    newSeries['y_true'] = newSeries['y_true'].astype(object)

    newSeries['user_index'] = row['json']['user_index']
    newSeries['precision'] = row['json']['precision']
    newSeries['recall'] = row['json']['recall']

    things1 = np.array(row['json']['y_pred']).astype('str')
    things2 = np.array(row['json']['y_true']).astype('str')
    y_pred_string = '[' + ', '.join(things1) + ']'
    y_true_string = '[' + ', '.join(things2) + ']'
    
    newSeries['y_pred'] = y_pred_string
    newSeries['y_true'] = y_true_string
    
    newSeries['len_yPred'] = len(row['json']['y_pred'])
    newSeries['len_yTrue'] = len(row['json']['y_true'])
    
    newDataframe.loc[index] = newSeries
    
newDataframe.describe()

       user_index  precision  recall
count  880.000000      880.0   880.0
mean   439.500000        0.0     0.0
std    254.178415        0.0     0.0
min      0.000000        0.0     0.0
25%    219.750000        0.0     0.0
50%    439.500000        0.0     0.0
75%    659.250000        0.0     0.0
max    879.000000        0.0     0.0

# Explore the results

Ideas why they might be terrible:
1. data sparsity
2. the projects are very similar but because they're not the same we get a bad recall

### Data Sparsity

In [24]:
test_user = newDataframe.iloc[879]
test_user

user_index                                         879
precision                                            0
recall                                               0
y_pred                        [63, 228, 513, 589, 745]
y_true        [209, 248, 257, 410, 413, 414, 674, 795]
len_yPred                                            5
len_yTrue                                            8
Name: 879, dtype: object

In [25]:
np.fromstring(test_user['y_pred'][1:-1], dtype=int, sep=', ')

array([ 63, 228, 513, 589, 745])

In [26]:
newDataframe

,user_index,precision,recall,y_pred,y_true,len_yPred,len_yTrue
0,0.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
1,1.0,0.0,0.0,"[63, 228, 513, 600, 796]",[],5,0
2,2.0,0.0,0.0,"[63, 513, 589, 600, 745]",[],5,0
3,3.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
4,4.0,0.0,0.0,"[228, 513, 589, 600, 796]",[],5,0
5,5.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
6,6.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
7,7.0,0.0,0.0,"[228, 513, 600, 745, 796]",[],5,0
8,8.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
9,9.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
10,10.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
11,11.0,0.0,0.0,"[513, 589, 600, 745, 826]",[],5,0
12,12.0,0.0,0.0,"[228, 513, 589, 600, 826]",[],5,0
13,13.0,0.0,0.0,"[63, 228, 513, 589, 600]",[],5,0
14,14.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
15,15.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
16,16.0,0.0,0.0,"[228, 513, 600, 796, 826]",[],5,0
17,17.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
18,18.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
19,19.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
20,20.0,0.0,0.0,"[63, 228, 513, 600, 745]",[],5,0
21,21.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
22,22.0,0.0,0.0,"[228, 449, 513, 589, 600]",[],5,0
23,23.0,0.0,0.0,"[63, 228, 513, 745, 796]",[],5,0
24,24.0,0.0,0.0,"[63, 228, 513, 589, 600]",[],5,0
25,25.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
26,26.0,0.0,0.0,"[63, 228, 513, 589, 600]",[],5,0
27,27.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
28,28.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
29,29.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
...,...,...,...,...,...,...,...
850,850.0,0.0,0.0,"[228, 513, 600, 745, 796]",[],5,0
851,851.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
852,852.0,0.0,0.0,"[228, 513, 589, 600, 826]",[],5,0
853,853.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
854,854.0,0.0,0.0,"[63, 228, 513, 600, 796]",[],5,0
855,855.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
856,856.0,0.0,0.0,"[63, 228, 513, 589, 745]",[],5,0
857,857.0,0.0,0.0,"[63, 228, 513, 600, 745]",[],5,0
858,858.0,0.0,0.0,"[63, 228, 513, 589, 600]",[],5,0
859,859.0,0.0,0.0,"[228, 513, 600, 745, 796]",[],5,0
860,860.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
861,861.0,0.0,0.0,"[63, 228, 513, 589, 600]",[],5,0
862,862.0,0.0,0.0,"[228, 513, 589, 600, 826]",[],5,0
863,863.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
864,864.0,0.0,0.0,"[63, 228, 513, 589, 745]",[],5,0
865,865.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
866,866.0,0.0,0.0,"[63, 228, 513, 589, 600]",[],5,0
867,867.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
868,868.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
869,869.0,0.0,0.0,"[228, 513, 589, 600, 796]",[],5,0
870,870.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
871,871.0,0.0,0.0,"[228, 513, 600, 745, 826]",[],5,0
872,872.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
873,873.0,0.0,0.0,"[63, 228, 513, 589, 826]",[],5,0
874,874.0,0.0,0.0,"[63, 228, 513, 589, 600]",[],5,0
875,875.0,0.0,0.0,"[228, 513, 600, 745, 796]",[],5,0
876,876.0,0.0,0.0,"[228, 513, 589, 600, 745]",[],5,0
877,877.0,0.0,0.0,"[63, 228, 513, 600, 745]",[],5,0
878,878.0,0.0,0.0,"[63, 228, 513, 589, 745]",[],5,0
879,879.0,0.0,0.0,"[63, 228, 513, 589, 745]","[209, 248, 257, 410, 413, 414, 674, 795]",5,8

In [30]:
# Find how many different projects were actually predicted
projects = []
for index, row in newDataframe.iterrows():
    projects = np.append(projects, np.fromstring(row['y_pred'][1:-1], dtype=int, sep=', '))

In [32]:
len(projects)

4400

In [35]:
len(set(projects))

11

So as we can see from above y_pred is the same almost everytime (unless presumably the user has already done one of the top projects). So I need to debug my code and figure out why that is happening