In [78]:
import pandas as pd
import json
import numpy as np

In [79]:
# Read results
results = pd.read_json('../../results-32_.json', lines=True)

In [80]:
results = results.T
results['json'] = results[0]

In [81]:
results

,0,json
0,"{'user_index': 1, 'precision': 0.0, 'recall': ...","{'user_index': 1, 'precision': 0.0, 'recall': ..."
1,"{'user_index': 2, 'precision': 0.0, 'recall': ...","{'user_index': 2, 'precision': 0.0, 'recall': ..."
2,"{'user_index': 3, 'precision': 0.0, 'recall': ...","{'user_index': 3, 'precision': 0.0, 'recall': ..."
3,"{'user_index': 4, 'precision': 0.0, 'recall': ...","{'user_index': 4, 'precision': 0.0, 'recall': ..."
4,"{'user_index': 5, 'precision': 0.0, 'recall': ...","{'user_index': 5, 'precision': 0.0, 'recall': ..."
5,"{'user_index': 6, 'precision': 0.0, 'recall': ...","{'user_index': 6, 'precision': 0.0, 'recall': ..."
6,"{'user_index': 7, 'precision': 0.0, 'recall': ...","{'user_index': 7, 'precision': 0.0, 'recall': ..."
7,"{'user_index': 8, 'precision': 0.0, 'recall': ...","{'user_index': 8, 'precision': 0.0, 'recall': ..."
8,"{'user_index': 9, 'precision': 0.0, 'recall': ...","{'user_index': 9, 'precision': 0.0, 'recall': ..."

In [82]:
newDataframe = pd.DataFrame(columns=['user_index', 'precision', 'recall', 'refined_precision', 'y_pred', 'y_true'])
newDataframe['y_pred'] = newDataframe['y_pred'].astype(object)
newDataframe['y_true'] = newDataframe['y_true'].astype(object)

for index, row in results.iterrows():
    newSeries = pd.Series(index=['user_index', 'precision', 'recall', 'refined_precision', 'y_pred', 'y_true'])
    newSeries['y_pred'] = newSeries['y_pred'].astype(object)
    newSeries['y_true'] = newSeries['y_true'].astype(object)

    newSeries['user_index'] = row['json']['user_index']
    newSeries['precision'] = row['json']['precision']
    newSeries['recall'] = row['json']['recall']
    newSeries['refined_precision'] = row['json']['refined_precision']

    things1 = np.array(row['json']['y_pred']).astype('str')
    things2 = np.array(row['json']['y_true']).astype('str')
    y_pred_string = '[' + ', '.join(things1) + ']'
    y_true_string = '[' + ', '.join(things2) + ']'
    
    newSeries['y_pred'] = y_pred_string
    newSeries['y_true'] = y_true_string
    
    newDataframe.loc[index] = newSeries

In [83]:
newDataframe

,user_index,precision,recall,refined_precision,y_pred,y_true
0,1.0,0.0,0.0,0.144088,"[244, 282, 780, 990, 1516]",[860]
1,2.0,0.0,0.0,-1.000000,"[158, 1194, 1224, 1497, 1598]",[]
2,3.0,0.0,0.0,-1.000000,"[590, 620, 812, 1050, 1423]",[]
3,4.0,0.0,0.0,-1.000000,"[56, 57, 968, 987, 1452]",[]
4,5.0,0.0,0.0,-1.000000,"[622, 991, 1368, 1468, 1500]",[]
5,6.0,0.0,0.0,-1.000000,"[126, 204, 487, 699, 923]",[]
6,7.0,0.0,0.0,-1.000000,"[315, 572, 885, 1439, 1499]",[]
7,8.0,0.0,0.0,-1.000000,"[174, 341, 624, 1452, 1735]",[]
8,9.0,0.0,0.0,0.101274,"[590, 712, 845, 1315, 1395]","[30, 353]"